### ISSUE TITLE
Keywords not visible on Page 1 of submission form (DOI: 10.5061/dryad.m0cfxpp69)

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1821] opened 2022-06-14 03:12 UTC
The keywords for this dataset appear in the preview on page 3, however, no keywords are visible on page 1 of the submission form.  Therefore, curators are unable to edit the keyword field. 

10.5061/dryad.k6djh9w8x
10.5061/dryad.m0cfxpp69

<img width="1242" alt="Screen Shot 2022-06-13 at 1 27 24 PM" src="https://user-images.githubusercontent.com/76497320/173485582-680ad7c1-12a8-4421-a90d-db1df9efb583.png">

Can you investigate?

**Comment by sfisher** [comment] 2022-06-16 23:05
This is a weird problem caused by people typing oddball subjects into the "research domain" which is a special "field of science" type of subject.  The keywords don't allow editing these field of science things.  The Field of Science usually automatically removes the previous values when it is changed, but in this case it it doesn't always change it, but piles more on top.

Added a fix for this and in the future, changing the value of the field of science and exiting the field should correctly reset it.  Also some fixes to prevent some orphan items in our tables.

Note to Self: I also noticed we had some unused (orphan) subjects which we can clean up after our deploy with a query like the one below.

```
DELETE sub_res.* FROM dcs_subjects_stash_engine_resources sub_res
LEFT JOIN dcs_subjects subj
ON sub_res.`subject_id` = subj.id
WHERE subj.id IS NULL;
```

**Closed** 2022-08-16 23:40 UTC
Labels: Curator Fix
