### ISSUE TITLE
First author email will not validate and edits cannot be submitted

### ISSUE THREAD

**Issue by LoriEP** [CDL-Dryad/dryad-product-roadmap#949] opened 2020-11-17 23:12 UTC
**Bug description:**
When editing a dataset and attempting to submit, intermittently the application will not recognize and validate that the first author email is entered in the email field.

**Steps to reproduce:**
Navigate to 10.5061/dryad.kh1893245 and try to submit changes, note that there is a red error message stating that "the first author must have an email supplied" (this error may not show each time but you cannot submit, the button will be greyed out)

**Expected behavior:**
When the first author has a valid email address, the system should verify that the author email is entered and allow edits to be submitted 

**Note:** Both curators and submitters have reported the issue. The current workaround is to add an email (duplicate first author email) in each individual co-author email field, then submit, then go back and remove them to re-submit to publish the dataset without duplicates. This issue is intermittent and I cannot find a commonality between the errors, but potentially it could have to do with email domain (foreign domains?)

[AuthorEmailIssue.mp4.zip](https://github.com/CDL-Dryad/dryad-product-roadmap/files/5556721/AuthorEmailIssue.mp4.zip)

Please see attached video

**Comment by ryscher** [comment] 2020-12-02 20:36
I made a slight change to the validation that *hopefully* fixes the problem. 

However, I was not able to reproduce the problem. Both the dataset with the DOI above and the dataset in the video have been corrected as part of normal curation.

If the issue occurs again, please let me know before you fix the problem, so I can verify exactly what is going wrong.

**Comment by ryscher** [comment] 2020-12-03 00:43
Lori found another item with this problem, and I was able to confirm that the underlying problem is fixed by my update.

**Closed** 2022-08-17 01:07 UTC
Labels: bug
