### ISSUE TITLE
Investigate what happened to availability of two datasets

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#1759] opened 2022-05-03 15:43 UTC
Two UCI datasets originally in Dash are now not available to be seen publicly, what could have caused this? https://datadryad.org/search?utf8=%E2%9C%93&q=antswers

**Comment by sfisher** [comment] 2022-05-05 23:05
These are a victim of https://github.com/CDL-Dryad/dryad-product-roadmap/issues/1754 which was likely caused by the rearranging of the engines. It didn't happen on most datasets but some had this problem from the search results depending on how many dots and slashes their identifier had.

They probably worked coming from the DOI but not from the search results since if you replace `%2F` with `/` (one is the encoded version of the other), then they work.

Fixed by https://github.com/CDL-Dryad/dryad-app/pull/840 .

**Closed** 2022-08-16 23:51 UTC
