### ISSUE TITLE
Authors unable to add files on "Upload Files" page

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1728] opened 2022-04-18 23:38 UTC
Several submitters have reported that they are unable to add files on "Upload Files" page. 
They all report that the grey progress bar stops progressing. 

One author mentioned, "the status changes immediately from pending to a grey bar. Afterwards nothing happens anymore (also not within 15min time) and when trying to proceed, the message appears "Finish upload before proceeding. Your files have not yet finished uploading." 

The same author of dataset 10.5061/dryad.f1vhhmh04, provided the following info: 
1) File types = .csv, .txt, .R
2) Browser = firefox version 99.0.1
3) Network settings that would prevent upload? = it neither worked via wifi nor mobile internet; it was checked that network settings do not prevent upload
4) connection speed was sufficient
5) Approx date/time of upload attempt = Failed upload attempts: 16th April (12:39 and several times thereafter), 17th April (00:20, 18:19)

I've added a screen capture, for reference. I'll add more instances and information as they are received. 

![image](https://user-images.githubusercontent.com/76497320/163893102-59f4f05f-332b-496a-9462-5e0dea2013c6.png)

**Comment by jleighherzog** [comment] 2022-04-19 00:06
10.5061/dryad.9w0vt4bhx
The zip files are directories that contain a variety of files (CSV, TRE, FASTA, TXT). 
I was attempting to upload them on Google Chrome v.100.0.4896.88 on a Mac (v.11.6.2).

**Comment by jleighherzog** [comment] 2022-04-19 00:14
10.5061/dryad.gqnk98sqf
I am trying to upload around 336 files, 6-7 MB each, as a single .zip file 1.58 GB in size from my own computer at home. I can select the file, select there is no personal info etc, and then I start the pending upload. But there is never any progress on the upload, the progress bar never changes and there is no indication that upload is happening.
4/18 @7:14pm

**Comment by sfisher** [comment] 2022-04-19 18:05
Hi @jleighherzog .  I've tried uploads with similarly sized zip files in Chrome and am not seeing these problems currently.

I don't doubt that some people are experiencing a problem sometimes, yet it will be difficult to solve it ourselves or report issues upstream (evaporate.js or Amazon) without more information to recreate the problem or find out where it is coming from since it could be from many places.  The library we're using also has 72 issues reported and not sure if any of them match or not. https://github.com/TTLabs/EvaporateJS/issues

If users are willing to troubleshoot or allow someone to see what it is happening then that is most useful.

## To troubleshoot more

When the problem is happening on the upload page:

1. Right click on the page anywhere.
2. Click **Inspect**.
![Screen Shot 2022-04-19 at 10 46 56 AM](https://user-images.githubusercontent.com/105433/164064918-4f16dd96-4cde-407d-b082-429df810cb6a.png)

3. A new pane will open either on the side or the bottom (of Google Chrome, Mozilla Firefox or MS Edge).
4. There are tab links in the panel, click the **console** tab in the panel.
![Screen Shot 2022-04-19 at 10 47 43 AM](https://user-images.githubusercontent.com/105433/164065151-7b4cee61-9a93-4cd8-b76b-d412ec37b66a.png)
.
5. Normally they will see a lot of messages about uploading different parts of the file and that is nothing to be concerned about, however they may see something different if they have problems.  (Example below is normal).
![Screen Shot 2022-04-19 at 10 48 47 AM](https://user-images.githubusercontent.com/105433/164065635-d747d48a-9ab5-4018-b2d1-4efae3b28fd5.png)
.
6. We need better information.  Can they either report anything unusual that looks like errors or else use "Select all" (CTRL-A or CMD-A), copy (CTRL-C or CMD-C).  Paste it into a text file and send it to us for troubleshooting?

---

## possible things that may cause issues

1. Network problems or unusual network settings on their end.
2. Service problems at Amazon and with S3.
3. Our server being down (we monitor and are notified and this isn't a common problem, but could happen).
4. They are not properly logged in or their user session has expired.  (I'd suggest logging out and back in and retrying the upload.)
5. Problems in the browser such as plugins, malware or other things that might interfere with network connections.
6. Network monitoring that incorrectly flags an upload as malicious and blocks it.

There are just so many things that could possibly cause problems that it's very difficult to guess what may be wrong without a lot more specific information and being able to get specific errors or create the problem.

**Comment by jleighherzog** [comment] 2022-04-19 18:33
@sfisher : Thank you. I had a feeling the info we were working to collect wasn't very useful. The detail you've provided is really helpful. We'll work to capture more in-depth information in order to provide you with what you need to troubleshoot.

**Comment by sfisher** [comment] 2022-04-19 19:46
Thanks for working through.  It will be interesting to see what is going on.  We're also fine getting on a zoom call with a user that's having a problem and that may help see what is going on when it's happening.

**Comment by jleighherzog** [comment] 2022-04-20 14:21
From the author of 10.5061/dryad.m63xsj447. 

> We followed the instructions you provided and I think the key error message is the following:
> Access to XMLHttpRequest at
> 'https://s3-us-west-2.amazonaws.com/dryad-s3-prd/173566/data/Artemisia_ultimate.csv?uploads'
> from origin 'https://www.datadryad.org' has been blocked by CORS policy:
> Response to preflight request doesn't pass access control check: No
> 'Access-Control-Allow-Origin' header is present on the requested
> resource.
> 
> It seems our files don't fulfill the CORS policy. Not sure what that
> means... we tried uploading with a different browser (Edge instead of
> Chrome) and the same problem occurred.

See attached file for error report:
[ERRORS.txt](https://github.com/CDL-Dryad/dryad-product-roadmap/files/8522284/ERRORS.txt)

**Closed** 2022-08-16 23:42 UTC
Labels: Curator Fix
