### ISSUE TITLE
Provide disambiguation for seemingly-duplicate RORs

### ISSUE THREAD

**Issue by hschubloom** [CDL-Dryad/dryad-product-roadmap#1392] opened 2021-07-22 22:25 UTC
The institutional affiliation 'China University of Geosciences' appears twice in the autofill dropdown when curating author affiliations. Please remove one of these from our integrated affiliations. Thanks!

**Comment by ryscher** [comment] 2023-04-14 17:40
Duplicate of #653

**Closed by ryscher** 2023-04-14 17:40 UTC
Labels: Curator Fix, UX
