### ISSUE TITLE
Ensure that links included in metadata and README sections open in external tab

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#3217] opened 2024-03-11 17:57 UTC
**Priority:** Low-medium
**Impact**: Future users will remain on Dryad page when clickingon links

If submissions contain links in the metadata fields (abstract, methods, etc.) and/or the README section, these links open in the  ‘current window’ instead of a ‘new window’. Please update so that, when clicked, users remain on the Dryad page and a new tab opens.

An example is here: https://datadryad.org/stash/dataset/doi:10.5061/dryad.j3tx95xfb (link in the README section)

**Comment by ahamelers** [comment] 2024-03-12 14:51
Duplicate of #3191, but this one is a bit more thoroughly described 😄

**Closed** 2024-04-04 20:35 UTC
Labels: curator feature request
