### ISSUE TITLE
Dataset not assigned correctly via API – PRIORITY

### ISSUE THREAD

**Issue by bryanmgee** [CDL-Dryad/dryad-product-roadmap#2131] opened 2022-11-22 15:52 UTC
There were two datasets created with this title: "_Scaling of activity space in marine organisms across latitudinal gradients_," both associated with the same American Naturalist MS.

**Dataset 1 DOI**: 10.5061/dryad.5qfttdz8n
**Status/history**: This dataset was created on August 29th via API but displays this message in the Activity Log: "Created by API user, assigned ownership to Dryad System (0)." A reminder email that the dataset was 'In Progress' was sent two days later, but because there is no submitting author information associated with it, it's not clear to who it was sent.

**Dataset 2 DOI**: 10.5061/dryad.h70rxwdmx
**Status/history**: This dataset was created on July 11th via API and displays the expected message: "Created by API user, assigned ownership to Vinay Udyawer (60948)." It was then auto-PPR'd and not accessed by the author again until, noticeably, August 29th. It then underwent several API revisions of metadata and author versioning in PPR before being auto-submitted last week via API, and upon curation checks (by me), published yesterday (Nov. 21st).

**Need to investigate**: Why was Dataset 1 auto-assigned to "Dryad System (0)"; and does/did the author to whom it was intended to be assigned (presumably the submitting author of Dataset 2) receive emails for Dataset 1? Follow-up: if Dataset 1 is sending emails to the submitting author of the now-published Dataset 2, we should permanently delete Dataset 1 (can't withdraw due to never having been submitted) to avoid future confusion with reminder 'In Progress' emails.

**Comment by ryscher** [comment] 2022-12-16 22:00
**Why was Dataset 1 auto-assigned to "Dryad System (0)"; and does/did the author to whom it was intended to be assigned (presumably the submitting author of Dataset 2) receive emails for Dataset 1?**

The assignment most likely happened this way due to the metadata that we received from Editorial Manager. Perhaps the user was not logged in to Editorial Manager, so it did not send the name or ORCID? I don't believe we would have sent the emails, since there was not an actual user attached to the dataset ownership.

** Follow-up: if Dataset 1 is sending emails to the submitting author of the now-published Dataset 2, we should permanently delete Dataset 1 (can't withdraw due to never having been submitted) to avoid future confusion with reminder 'In Progress' emails.**

I have deleted the duplicate unpublished dataset, which only had basic metadata imported from the journal. It did not have any data files.

**Closed by ryscher** 2022-12-16 22:00 UTC
Labels: Curator Fix
