### ISSUE TITLE
Bring curator and institution filters (admin dashboard)

### ISSUE THREAD

**Issue by rcurty** [CDL-Dryad/dryad-product-roadmap#2654] opened 2023-07-11 21:34 UTC
The curator and institution filters are missing from the admin dashboard. These filters are essential to sort the deposits and find those assigned to us or affiliated with our campus more easily.

**Comment by rcurty** [comment] 2023-07-11 21:36
relates to Issue #2653

**Comment by ahamelers** [comment] 2023-07-13 12:47
Duplicate of #2653

**Closed by ahamelers** 2023-07-13 12:47 UTC
Labels: bug
