### ISSUE TITLE
Dataset not able to download

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#1209] opened 2021-04-12 14:00 UTC
I believe it was a ONEShare dataset but it's a UCSC researcher who let me know that he cannot download the files or dataset from: https://datadryad.org/stash/dataset/doi:10.15146/5xcp-0d46

Confirmed this as well - wondering if it's a collections issue?

**Comment by sfisher** [comment] 2021-04-15 19:04
Moving my comments down here, since it was confusing when I put in the body of the comment.
---

This caused by the collections issue https://github.com/CDLUC3/mrt-doc/issues/637 I filed for the Merritt team.

It seems like there were two DataONE collections (one for DataUP and one for DataONE) and it seems like most things in the DataONE collection were not migrated correctly, but just DataUP.  They both used the same account for access and same tenant id on our side but were separate collections in Merritt, I believe.

**Comment by elopatin-uc3** [comment] 2021-04-15 20:27
@dlowenberg David Loy's work on Audit service improvements has taken priority over [mrt-doc#637](https://github.com/CDLUC3/mrt-doc/issues/637). Once he has deployed these changes, we can get back to migrating the DataONE Dash collection to Dryad. In the meantime, I can establish public access to DataONE Dash collection in Merritt if that would be appropriate and helpful for the researcher at UCSC. Let me know.

**Comment by dlowenberg** [comment] 2021-04-15 20:31
I'm not sure what is best for Merritt (e.g., opening up the collection) but I know that this is affecting our service and making the dataset unusable so whatever can be done to fix this is appreciated. The researcher is waiting for us to be able to allow access again to his data. Thanks

**Comment by elopatin-uc3** [comment] 2021-04-15 20:35
Was the DataONE Dash collection publicly available in the past? I believe it was. If you can confirm, I'll go ahead an open it up. Then, once the migration is done, we'll close it and delete its content.

**Closed** 2022-08-17 01:03 UTC
Labels: Curator Fix
