### ISSUE TITLE
Provision new production RDS database in AWS

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#319] opened 2019-05-23 20:44 UTC
We need a dryad production database to write migration data to.  This will be a task for ITS and Marisa and Jim are working with them to provision it.

The database should be accessible from our current stage instance `uc3-dryadui-stg-2c.cdlib.org` .

**Comment by sfisher** [comment] 2019-05-23 22:38
We will do it on stage database server and then export it to production.

**Comment by marisastrong** [comment] 2019-05-23 22:39
We will be creating a new RDS Stage instance to house the migration db.  This will keep us from accidentally writing content to the other stage db.

**Comment by marisastrong** [comment] 2019-05-24 00:50
I requested a new RDS Production instance.  **rds-uc3-dryad-prd.**  Reasons being: At some point we should be using an RDS instance named Dryad for naming consistency.  Also since this is a new instance, we can request that access be allowed from the stage environment (this is not uncommon).  And writing to a separate production instance, will prevent us from accidentally writing content to stage db.  We'll see if IAS grants our request, if not, we'll use the current Dash2 RDS stage instance.  
I'll update the ticket when we know more.  
I requested Need by date of 5/31.

**Comment by marisastrong** [comment] 2019-05-30 20:54
rds-uc3-dryad-prd has been provisioned.  I will provide information regarding account information under separate cover.

Please confirm access to the database using the command provided in the cover.

**Comment by marisastrong** [comment] 2019-05-30 23:14
@sfisher confirmed he can access the db from the stage server.  closing

**Closed by marisastrong** 2019-05-30 23:14 UTC
Labels: Migration Server Setup
