### ISSUE TITLE
Dataset(s) stuck in 'Processing' (DOI: 10.5061/dryad.1c59zw3zb and 10.5061/dryad.08kprr55h)

### ISSUE THREAD

**Issue by Ariana-Orona** [CDL-Dryad/dryad-product-roadmap#1930] opened 2022-08-18 16:49 UTC
The author has reached out, because, after they performed edits, they no longer have access to either dataset. The Activity Log of each dataset notes that the status is 'In Progress' although the Admin Dashboard view notes the status is 'Processing.' Can you please change the dataset status to 'Submitted' if all of the required fields are included?

**Comment by Ariana-Orona** [comment] 2022-08-18 17:25
This one is also stuck 'In Processing' (DOI: 10.7280/D14H60). Can you investigate this as well, please?

**Comment by sfisher** [comment] 2022-08-18 20:22
This appears to be a Merritt repository problem.  While these were submitted a while ago and they gave us receipt for the submission, they still haven't finished in their system.  I'll ask them to look into the issues.

**Comment by sfisher** [comment] 2022-08-18 21:21
I contacted the Merritt team and they fixed the problem and people should have seen these go through now.

**Comment by Ariana-Orona** [comment] 2022-08-18 23:49
@sfisher thank you! Can you also check in on this one? 10.5061/dryad.jdfn2z3dp It has been stuck 'In Processing' for about ~50 minutes now. Should we expect delays for now? If so, when should we bring up datasets that are seem to be stuck?

**Comment by sfisher** [comment] 2022-08-19 00:34
It looks like the same problem from our side.  What happens is that we get an acceptance/success notice from them but it has a problem going into their system.  IDK why this is happening.  They pushed some through and looked at it.  I'll let them know about this one, also, not sure if they'll do anything about it until the morning at this point.

**Comment by sfisher** [comment] 2022-08-19 00:40
But yes, if you have lists of stuff that's not going through that is fine to report them.  I think I can get some idea by looking at our submission records if they take a very long time to show up as completed after Merritt said they were ingested.

**Comment by Ariana-Orona** [comment] 2022-08-19 00:51
@sfisher got it, will do. Thank you for looking into this :)

**Comment by sfisher** [comment] 2022-08-22 16:58
@Ariana-Orona  Merritt tells me they believe the problem is fixed now again.  I double-checked and there weren't any problem ones from the weekend.  I'll continue to monitor over the next few days, but let me know if you see any more stall like this.

**Closed** 2022-08-30 23:43 UTC
Labels: Curator Fix
