### ISSUE TITLE
Unable to download dataset

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1204] opened 2021-04-05 14:56 UTC
**Bug description:**
Unable to download data for this submission: 
Title: _Data from: Queuine is a nutritional regulator of Entamoeba histolytica response to oxidative stress and a virulence attenuator_
DOI: 10.5061/dryad.rv15dv465

**Steps to reproduce:**
When "Download Dataset" is selected AND/OR when attempting to select individual files for download, both options fail to initiate download

**Expected behavior: **
When "Download Dataset" is selected, the files automatically begin to download

**Comment by sfisher** [comment] 2021-04-05 17:00
This is caused by a Merritt (storage repo) issue that happens infrequently where one version gets sent to a different dataset than the other versions because of some problem with local ids.  I contacted them for them to make a recommendation of the best way for us to fix it.  We have all the files, I think, just separated weirdly.

Technical info.

```
doi: 10.5061/dryad.rv15dv465
identifier_id: 52923

resources
---------
id	updated_at	version
79187	2020-09-04 11:32:02	1
108488	2021-03-12 21:38:45	2
109564	2021-03-12 21:42:02	3
109622	2021-03-15 19:18:35	4
109966	2021-03-16 06:58:02	5
110087	2021-03-16 18:40:37	6
-----------------------------
```

One dataset has version 1, 2nd dataset has version 2-6 (as 1-5).

```
--first one--
erc:	
who:	Ankri, Serge
what:	Supplemental tables and Figures
when:	2020
where:	ark:/13030/m56452bt
where:	doi:10.5061/dryad.rv15dv465

--second one--
erc:	
who:	Ankri, Serge
what:	Data from: Queuine is a nutritional regulator of Entamoeba histolytica
      response to oxidative stress and a virulence attenuator
when:	2020
where:	ark:/13030/m5519p90
where:	doi:10.5061/dryad.rv15dv465
```

**Comment by sfisher** [comment] 2021-04-06 23:15
Adding resource_id 113647 to add these files from a separate dataset that was in Merritt.  Once it goes through I'll adjust the versions to make it work and the date back to March 16.

**Comment by sfisher** [comment] 2021-04-07 01:51
This is fixed now and everything downloads.

**Closed** 2022-08-17 01:03 UTC
Labels: Curator Fix
