### ISSUE TITLE
Error when attempting to enter editing mode (DOI: 10.5061/dryad.1c59zw3xp)

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1735] opened 2022-04-22 00:04 UTC
When attempting to edit the dataset, the author and I are both receiving the error message attached. Any ideas what might be causing the issue? 

<img width="572" alt="Screen Shot 2022-04-21 at 6 59 55 PM" src="https://user-images.githubusercontent.com/76497320/164569945-4036ff6d-5c00-4a53-836f-d1990b42a024.png">

**Comment by sfisher** [comment] 2022-04-22 00:53
This should be fixed for this dataset.  Caused by bad data in the author email (two emails smashed into one from editorial manager) which made it unable to correctly validate and create a new version.

I put in a ticket for this so we can look at how to fix if we get bad data like this in the future.

**Closed** 2022-08-16 23:46 UTC
Labels: Curator Fix
