### ISSUE TITLE
Locking certain statuses

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#180] opened 2019-01-15 21:25 UTC
The statuses below mean that when popping open the "status edit pencil" dialog, only certain items will likely be available.  (Thanks, Daniella)

----

Unsubmitted: The status where a researcher is working on the submission - no one is able to do anything while they are in this state. It is visible in the Admin layer but no status changes are available to anyone.

Author Action Required: Similar to Unsubmitted - it is with the Author but no lock outs need to happen.

Once the dataset has been published, the dataset can be versioned at which point it could go back through any of these statuses once the Author initiates the editing of it (which would while they are editing it put it back into Unsubmitted). Anytime an author clicks "Submit" it goes to "Submitted" and the lead curator publishes it (if versioned) or sends it back through curation.

**Comment by briri** [comment] 2019-02-05 23:45
is this a duplicate of #185?

**Closed** 2022-08-17 01:15 UTC
Labels: Workflow, UI
